In [1]:
import pandas as pd
import torch

In [2]:
trainDF = pd.read_csv("train.csv")
testDF = pd.read_csv("test.csv")


In [3]:
trainData = trainDF.values
testData = testDF.values

In [4]:
trainXNumpy, trainYNumpy = trainData[:,:-1], trainData[:, -1] #gets all columns but last column (features), gets last column for the results (labels)
testXNumpy, testYNumpy = testData[:, :-1], testData[:, -1]

In [5]:
trainX = torch.tensor(trainXNumpy, dtype=torch.float64)
trainY = torch.tensor(trainYNumpy, dtype=torch.float64)
testX = torch.tensor(testXNumpy, dtype=torch.float64)
testY = torch.tensor(testYNumpy, dtype=torch.float64)

In [8]:
print(trainX[:5])
print(trainY[:5])

tensor([[ 24.,  51.,  44.,  51.,  60.,  75.,  72.,  61.,  27.,   0.],
        [ 22.,  31., 214., 177.,  62.,  46.,  24.,   9.,   0.,   0.],
        [ 84., 126., 239., 194., 159., 171., 125.,  74.,  24.,   8.],
        [ 65.,  76.,  80., 110.,  82.,  81.,  55.,  49.,  56.,  34.],
        [ 99., 107., 339., 287., 139., 147., 110.,  71.,  37.,   0.]],
       dtype=torch.float64)
tensor([ 3.,  2.,  9.,  7., 12.], dtype=torch.float64)


In [12]:
#Q1: about how many bytes does trainX consume?
print(trainX.numel()) #number of elements in the tensor
#from float64 it means there are 64/8 = 8 bytes each element
#10440 x 8 = 83520

10440


In [21]:
#Q2: what is the biggest difference we would have any one cell if we used float16 instead of float64?
trainX16 = torch.tensor(trainXNumpy, dtype=torch.float16)
#print(trainX16[:5])
trainX64 = trainX16.to(torch.float64)
difference = trainX - trainX64
maxFloat = torch.max(difference).item()
print(maxFloat) #dont know if the answer is supposed to be 0, but to me it makes sense? 

0.0


In [22]:
#Q3: is a CUDA GPU available on your VM?
print(torch.cuda.is_available())

False


In [25]:
coef = torch.tensor([
        [0.0040],
        [0.0040],
        [0.0040],
        [0.0040],
        [0.0040],
        [0.0040], # POS_50_59_CP
        [0.0300], # POS_60_69_CP
        [0.0300],
        [0.0300],
        [0.0300]
], dtype=trainX.dtype)
coef

tensor([[0.0040],
        [0.0040],
        [0.0040],
        [0.0040],
        [0.0040],
        [0.0040],
        [0.0300],
        [0.0300],
        [0.0300],
        [0.0300]], dtype=torch.float64)

In [30]:
#Q4: what is the predicted number of deaths for the first census tract?
print(torch.matmul(testX[0], coef).item())
#9.844

9.844


In [31]:
#Q5: what is the average number of predicted deaths, over the whole testX dataset?
predictedDeaths = torch.matmul(testX,coef)
print(torch.mean(predictedDeaths).item())
#12.073632183908048


12.073632183908048


In [34]:
#Q6: first, what is y when x is a tensor containing 0.0?
x = torch.tensor(0.0)
y = x**2 -8*x +19
float(y)
#19.0, but not sure if im doing this one correctly

19.0